name: admob_consent_example
description: Demonstrates how to use the admob_consent plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  admob_consent:
    path: ../

flutter:
  uses-material-design: true
