name: admob_consent
description: A wrapper for Google's User Messaging Platform (UMP) SDK, used for consent gathering (i.e. GDPR, ATT) on Android and iOS.
version: 2.0.0
homepage: https://www.anteger.com
repository: https://github.com/gimu/admob_consent
issue_tracker: https://github.com/gimu/admob_consent/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.anteger.admob_consent
        pluginClass: AdmobConsentPlugin
      ios:
        pluginClass: AdmobConsentPlugin
